### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model that stores cars direction in JavaScript.
- [x] Add classes to car for directions in HTML.
- [x] Add CSS to change cars direction.
- [x] Create variable(s) for events: class (direction) in JavaScript.
- [x] Create event listener for keydown on document in JavaScript.
- [x] Update car direction based on key pressed in JavaScript.
