### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to the data model that holds cars x and y coordinates in JavaScript.
- [x] Use absolute positioning for image in CSS.
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Move the car every 16ms for a smooth movement.
